export const ALGERIAN_WILAYAS = [
  
                                "Ain Benian (Alger)",
                                "Ain Taya",
                                "Alger-Centre",
                                "Bab El Oued",
                                "Bab Ezzouar",
                                "Baba Hassen",
                                "Bachdjarah",
                                "Baraki",
                                "Ben Aknoun",
                                "Beni Messous",
                                "Bir Mourad Rais",
                                "Birkhadem",
                                "Birtouta",
                                "Bologhine",
                                "Bordj El Bahri",
                                "Bordj El Kiffan",
                                "Boubouba",
                                "Bouzereah",
                                "Casbah",
                                "Cheraga",
                                "Dar El Beida",
                                "Dely Ibrahim",
                                "Djasr Kasentina",
                                "Douera",
                                "Draria",
                                "El Achour",
                                "El Biar",
                                "El Harrach",
                                "El Madania",
                                "El Magharia",
                                "El Marsa (Alger)",
                                "El Mouradia",
                                "Eucalyptus",
                                "Hamma Annassers",
                                "Hammamet (Alger)",
                                "Harraoua",
                                "Hussein Dey",
                                "Hydra",
                                "Khraicia",
                                "Kouba",
                                "Mahelma",
                                "Mohammadia (Alger)",
                                "Oued Koreiche",
                                "Oued Smar",
                                "Ouled Chebel",
                                "Ouled Fayet",
                                "Rahmania",
                                "Rais Hamidou",
                                "Reghaia",
                                "Rouiba",
                                "Saoula",
                                "Sidi M\u0027Hamed (Alger)",
                                "Sidi Moussa",
                                "Souidania",
                                "Staoueli",
                                "Tessala El Merdja",
                                "Zeralda"
] as const;

export type AlgerianWilaya = typeof ALGERIAN_WILAYAS[number];
